### ISSUE TITLE
[BE] health check API 추가

### ISSUE THREAD

**Issue by xi-jjun** [choorai/excuse-me-backend#3]
## 배경 & 목적
향후 인프라에 배포 시 AWS ALB와 같은 서비스를 쓰게 되면, health-check API를 만들어야 하는 부분이 존재.
그 외 서버의 동작을 로컬에서 간단하게 확인하기 위한 API로써의 역할도 있고, 기획과 무관하게 진행될 수 있는 부분이기에 진행.

## 요구사항
health-check api를 개발한다.
- URI : `/health-check`
- 접근 범위 : 전체 접근 가능

**Comment by somefood** [comment]
@xi-jjun @seokhwan-an @JoungMinJu 
혹시 이 부분 스프링 엑츄에이터 쓰신 분 있으심까?
살짝 깔아서 봤는데, health check API가 있던데 활용하신 분 있는지 궁금함미다 ㅎㅎ

**Comment by xi-jjun** [comment]
@somefood 
저도 살짝 확인해봤는데, health-check api 외에도 매우 다양한 모니터링 관련 기능(heapdump, 메모리 사용량 확인 등등)이 있어서 잘 써보면 좋을 것 같다는 생각을 했습니다!
하지만 이번 작업에서는 범위를 health-check API 한정으로 정했기 때문에 나머지 부가 기능들은 향후 티켓 만들어서 진행되면 좋을 것 같습니다!
