### ISSUE TITLE
[BE] Jwt 인증 기능 추가

### ISSUE THREAD

**Issue by xi-jjun** [choorai/excuse-me-backend#6]
is blocked by https://github.com/choorai/excuse-me-backend/issues/5
위 작업이 진행된 후 현재 작업이 진행될 수 있습니다.

## 요구사항
- JWT 인증 필터 추가

## 참고
![Image](https://github.com/choorai/excuse-me-backend/assets/60127396/912838a6-d63b-4b0e-9f8a-52b881746416)

- [Spring security + boot 3 + JWT 인증](https://www.youtube.com/watch?v=BVdQ3iuovg0&t=5910s)
- [인프런 JWT 인증 구현(무료)](https://www.inflearn.com/course/lecture?courseSlug=%EC%BD%94%ED%8B%80%EB%A6%B0%EA%B3%BC-spring-security-jwt-%ED%9A%8C%EC%9B%90%EA%B0%80%EC%9E%85%EB%A7%8C%EB%93%A4%EA%B8%B0&unitId=167589&tab=curriculum)

**Comment by xi-jjun** [comment]
@JoungMinJu 실제 구현들어가기 전에 간단하게 Security + JWT 인증 과정(위 사진)과 구현 방안에 대해서 간단하게 설명드릴게요!
시작하시게 될 때 말씀주세요!

**Comment by JoungMinJu** [comment]
> @JoungMinJu 실제 구현들어가기 전에 간단하게 Security + JWT 인증 과정(위 사진)과 구현 방안에 대해서 간단하게 설명드릴게요! 시작하시게 될 때 말씀주세요!

네 주말 일정때문에 해도 다음주 되어서야 시작할 수 있을 것 같아요 🥲

**Comment by somefood** [comment]
https://velog.io/@junho5336/SpringBoot-%EB%A1%9C%EA%B7%B8%EC%9D%B8-%EA%B5%AC%ED%98%84%ED%95%98%EA%B8%B0-with.-SpringSecurity-JWT

참고
